version: 2
updates:
  # Create PRs for images in Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  # Create PRs for images in node/Dockerfile
  - package-ecosystem: docker
    directory: /node
    schedule:
      interval: daily
